apiVersion: v2
name: topograph
description: Discovers the physical network topology of a cluster and exposes it to schedulers.
kubeVersion: ">=1.27.0-0"
type: application
version: 0.6.0
appVersion: "v0.5.0"

home: https://github.com/NVIDIA/topograph
icon: https://raw.githubusercontent.com/NVIDIA/topograph/main/docs/assets/topograph-logo.png
sources:
  - https://github.com/NVIDIA/topograph
maintainers:
  - name: NVIDIA CORPORATION
    url: https://www.nvidia.com
keywords:
  - topograph
  - topology
  - kubernetes
  - slurm
  - slinky
  - infiniband
  - gpu
  - scheduling
annotations:
  org.opencontainers.image.title: Topograph
  org.opencontainers.image.description: Discovers the physical network topology of a cluster and exposes it to schedulers.
  org.opencontainers.image.vendor: NVIDIA
  org.opencontainers.image.licenses: Apache-2.0
  org.opencontainers.image.source: https://github.com/NVIDIA/topograph
  org.opencontainers.image.documentation: https://github.com/NVIDIA/topograph/blob/main/docs/overview.md
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/NVIDIA/topograph/blob/main/docs/overview.md
    - name: Chart Source
      url: https://github.com/NVIDIA/topograph/tree/main/charts/topograph

dependencies:
  - name: node-data-broker
    version: 0.5.0
    repository: "file://charts/node-data-broker"
  - name: node-observer
    version: 0.5.0
    repository: "file://charts/node-observer"
